/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import Entidades.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author MARCO RENÉ ESQUIVEL JUÁREZ
 */
public class LabPOO extends javax.swing.JFrame {

    /**
     * Creates new form LabPOO
     */
    public LabPOO() {
        initComponents();
        limpiar();
        this.jComboBox1.setSelectedIndex(-1);
        
    }
    private void limpiar(){
        this.jComboBox1.setSelectedIndex(-1);
        this.txtNombre.setText("");
        this.jFormattedTextField1.setValue(0);
        this.spnOficinas.setValue(1);
        this.spnPlantas.setValue(1);
    }
    
    private void validar(){
        this.spnOficinas.setEnabled(false);
        this.spnPlantas.setEnabled(false);
        switch(this.jComboBox1.getSelectedIndex()){
            case 0:
                this.spnOficinas.setEnabled(false);
                this.spnPlantas.setEnabled(false);               
                break;
            case 1:
                this.spnOficinas.setEnabled(true);
                this.spnPlantas.setEnabled(true);
                break;
            case 2:
                this.spnOficinas.setEnabled(true);
                this.spnPlantas.setEnabled(true);
                break;
            default:
                this.spnOficinas.setEnabled(false);
                this.spnPlantas.setEnabled(false);   
                break;
        }
    }
    private String tipo(int x){
        String t = "";
        switch(x){
            case 0:
                t = "Polideportivo";
                break;
            case 1:
                t = "Educacional";
                break;
            case 2:
                t = "Hospitalario";
                break;
        } 
        return t;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        spnOficinas = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spnPlantas = new javax.swing.JSpinner();
        btnConstruir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblSeHa = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblTip = new javax.swing.JLabel();
        lblSup = new javax.swing.JLabel();
        lblOf = new javax.swing.JLabel();
        lblPlan = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(14, 77, 164));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Construcciones");

        jPanel4.setBackground(new java.awt.Color(223, 225, 222));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 77, 164));
        jLabel5.setText("Especificaciones");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre del edificio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tipo Edificio");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polideportivo", "Educacional", "Hospitalario" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Superficie m^2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Oficinas");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.##"))));

        spnOficinas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Plantas");

        spnPlantas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnConstruir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConstruir.setText("Construir");
        btnConstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstruirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField1)
                                    .addComponent(spnPlantas)
                                    .addComponent(spnOficinas, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnConstruir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnOficinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spnPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConstruir)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel8.setMaximumSize(new java.awt.Dimension(202, 132));
        jLabel8.setMinimumSize(new java.awt.Dimension(202, 132));
        jLabel8.setPreferredSize(new java.awt.Dimension(202, 132));

        lblSeHa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPlan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSeHa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeHa, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTip, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSup, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOf, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        validar();
        //Construccion polideportivo = new Construccion(this.txtNombre.getText(), this.jComboBox1.getSelectedIndex(), Double.parseDouble(this.jFormattedTextField1.getValue().toString()));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void btnConstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstruirActionPerformed

        if (!"".equals(this.txtNombre.getText()) && Double.parseDouble(this.jFormattedTextField1.getValue().toString()) > 0) {
            switch(this.jComboBox1.getSelectedIndex()){
                case 0:
                    Construccion polideportivo = new Construccion(this.txtNombre.getText(), this.jComboBox1.getSelectedIndex(), Double.parseDouble(this.jFormattedTextField1.getValue().toString()));              
                    this.jLabel8.setIcon(new ImageIcon("Polidep.png"));
                    this.lblSeHa.setText("¡Se ha construido un POLIDEPORTIVO.!");
                    this.lblNom.setText("Nombre: "+ polideportivo.getNombre());
                    this.lblTip.setText("Tipo: "+tipo(polideportivo.getTipoEd()));
                    this.lblSup.setText("Superficie: "+ polideportivo.getSuperficieEd()+ " m^2");
                    break;
                case 1:
                    ConstruccionConOficinas educacional = new ConstruccionConOficinas(this.txtNombre.getText(), this.jComboBox1.getSelectedIndex(), Double.parseDouble(this.jFormattedTextField1.getValue().toString()), Integer.parseInt(this.spnOficinas.getValue().toString()), Integer.parseInt(this.spnPlantas.getValue().toString()));
                    this.jLabel8.setIcon(new ImageIcon("Educ.jpg"));
                    this.lblSeHa.setText("¡Se ha construido un Edificio Educacional.!");
                    this.lblNom.setText("Nombre: "+ educacional.getNombre());
                    this.lblTip.setText("Tipo: "+tipo(educacional.getTipoEd()));
                    this.lblSup.setText("Superficie: "+ educacional.getSuperficieEd()+ " m^2");
                    this.lblOf.setText("Oficinas: "+ educacional.getCantOficinas());
                    this.lblPlan.setText("Plantas: " + educacional.getCantPlantas());
                    break;
                case 2:
                    ConstruccionConOficinas hospitalario = new ConstruccionConOficinas(this.txtNombre.getText(), this.jComboBox1.getSelectedIndex(), Double.parseDouble(this.jFormattedTextField1.getValue().toString()), Integer.parseInt(this.spnOficinas.getValue().toString()), Integer.parseInt(this.spnPlantas.getValue().toString()));
                    this.jLabel8.setIcon(new ImageIcon("hosp.png"));
                    this.lblSeHa.setText("¡Se ha construido un Edificio Hospitalario.!");
                    this.lblNom.setText("Nombre: "+ hospitalario.getNombre());
                    this.lblTip.setText("Tipo: "+tipo(hospitalario.getTipoEd()));
                    this.lblSup.setText("Superficie: "+ hospitalario.getSuperficieEd()+ " m^2");
                    this.lblOf.setText("Oficinas: "+ hospitalario.getCantOficinas());
                    this.lblPlan.setText("Plantas: " + hospitalario.getCantPlantas());
                    break;
                default:
                    break;
            }        
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los valores requeridos");
        }
        limpiar();
    }//GEN-LAST:event_btnConstruirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabPOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConstruir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblOf;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JLabel lblSeHa;
    private javax.swing.JLabel lblSup;
    private javax.swing.JLabel lblTip;
    private javax.swing.JSpinner spnOficinas;
    private javax.swing.JSpinner spnPlantas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
